const EducationLevel = { COLLEGE: "COLLEGE", HIGH_SCHOOL: "HIGH_SCHOOL" };
const Permission = {
  FRIENDS: "FRIENDS",
  ONLY_ME: "ONLY_ME",
  PUBLIC: "PUBLIC",
};
const RelationshipStatus = {
  SINGLE: "SINGLE",
  IN_A_RELATIONSHIP: "IN_A_RELATIONSHIP",
  ENGAGED: "ENGAGED",
  MARRIED: "MARRIED",
  IN_A_CIVIL_UNION: "IN_A_CIVIL_UNION",
  IN_A_DOMESTIC_PARTNERSHIP: "IN_A_DOMESTIC_PARTNERSHIP",
  IN_AN_OPEN_RELATIONSHIP: "IN_AN_OPEN_RELATIONSHIP",
  IT_IS_COMPLICATED: "IT_IS_COMPLICATED",
  SEPARATED: "SEPARATED",
  DIVORCED: "DIVORCED",
  WIDOWED: "WIDOWED",
};

const AUTHENTICATED_USER_ID = "1";

const COMMENTS_LIST = [
  {
    id: "post-0-comment-0",
    dateTime: "Sun, 22 Jan 2023 18:02:47 GMT",
    owner: {
      id: "1",
      email: "darius.fieraru@mail.com",
      firstName: "Darius",
      lastName: "Fieraru",
      username: "darius.fieraru",
    },
    postId: "post-0",
    reactions: [
      {
        id: "post-0-comment-0-reaction-0",
        dateTime: "Sun, 22 Jan 2023 20:01:39 GMT",
        owner: {
          id: "0",
          email: "olivia.constantin@mail.com",
          firstName: "Olivia",
          lastName: "Constantin",
          username: "olivia.constantin",
        },
        type: "LIKE",
      },
    ],
    replies: [
      {
        id: "post-0-comment-0-reply-0",
        dateTime: "Mon, 23 Jan 2023 14:01:47 GMT",
        owner: {
          id: "0",
          email: "olivia.constantin@mail.com",
          firstName: "Olivia",
          lastName: "Constantin",
          username: "olivia.constantin",
        },
        postId: "post-0",
        reactions: null,
        replies: [
          {
            id: "post-0-comment-0-reply-0-reply-0",
            dateTime: "Tue, 24 Jan 2023 15:27:58 GMT",
            owner: {
              id: "1",
              email: "darius.fieraru@mail.com",
              firstName: "Darius",
              lastName: "Fieraru",
              username: "darius.fieraru",
            },
            postId: "post-0",
            reactions: null,
            replies: null,
            text: "ez",
          },
          {
            id: "post-0-comment-0-reply-0-reply-1",
            dateTime: "Tue, 24 Jan 2023 16:29:51 GMT",
            owner: {
              id: "1",
              email: "darius.fieraru@mail.com",
              firstName: "Darius",
              lastName: "Fieraru",
              username: "darius.fieraru",
            },
            postId: "post-0",
            reactions: null,
            replies: null,
            text: "lejerrr",
          },
        ],
        text: "TY",
      },
    ],
    text: "So beautiful...",
  },
  {
    id: "post-0-comment-1",
    dateTime: "Tue, 24 Jan 2023 08:26:02 GMT",
    owner: {
      id: "0",
      email: "olivia.constantin@mail.com",
      firstName: "Olivia",
      lastName: "Constantin",
      username: "olivia.constantin",
    },
    postId: "post-0",
    reactions: null,
    replies: null,
    text: "The best trip ever!",
  },
];

const POST_PHOTOS_LIST = [
  {
    id: "post-0-photo-0",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://cdn.britannica.com/82/195482-050-2373E635/Amalfi-Italy.jpg",
  },
  {
    id: "post-0-photo-1",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://static.independent.co.uk/2021/08/10/15/iStock-1271579758.jpg",
  },
  {
    id: "post-0-photo-2",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://deih43ym53wif.cloudfront.net/amalfi-italy-shutterstock_759048709_bdda191300.jpeg",
  },
  {
    id: "post-0-photo-3",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://i0.wp.com/handluggageonly.co.uk/wp-content/uploads/2016/03/Positano-Weather.jpg?fit=1600%2C1066&ssl=1",
  },
  {
    id: "post-0-photo-4",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://wise.com/imaginary/pros-and-cons-living-in-italy.jpg",
  },
  {
    id: "post-0-photo-5",
    comments: null,
    ownerId: "0",
    postId: "post-0",
    reactions: null,
    shares: null,
    text: null,
    url: "https://i0.wp.com/www.nothingfamiliar.com/wp-content/uploads/2022/02/Things-to-do-in-Venice-Italy.jpg",
  },
];

const POSTS_LIST = [
  {
    id: "post-0",
    canComment: "FRIENDS",
    canReact: "FRIENDS",
    canShare: "FRIENDS",
    canView: "FRIENDS",
    dateTime: "Sun, 22 Jan 2023 17:43:07 GMT",
    owner: {
      id: "0",
      email: "olivia.constantin@mail.com",
      firstName: "Olivia",
      lastName: "Constantin",
      username: "olivia.constantin",
    },
    parentId: null,
    reactions: [
      {
        id: "post-0-reaction-0",
        owner: {
          id: "0",
          email: "olivia.constantin@mail.com",
          firstName: "Olivia",
          lastName: "Constantin",
          username: "olivia.constantin",
        },
        type: "LOVE",
      },
    ],
    shares: [
      {
        id: "post-0-share-0",
        dateTime: "Sun, 22 Jan 2023 19:45:06 GMT",
        owner: {
          id: "1",
          email: "darius.fieraru@mail.com",
          firstName: "Darius",
          lastName: "Fieraru",
          username: "darius.fieraru",
        },
      },
    ],
    text: "Italy",
    video: null,
  },
  {
    id: "post-1",
    canComment: "FRIENDS",
    canReact: "FRIENDS",
    canShare: "FRIENDS",
    canView: "FRIENDS",
    dateTime: "Thu, 02 Feb 2023 08:21:49 GMT",
    owner: {
      id: "0",
      email: "olivia.constantin@mail.com",
      firstName: "Olivia",
      lastName: "Constantin",
      username: "olivia.constantin",
    },
    parentId: null,
    photos: null,
    reactions: null,
    shares: null,
    text: "Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!",
    video: null,
  },
];

const USERS_LIST = [
  {
    id: "0",
    biography:
      "She's eager, responsible, polite and perhaps a little too uncontrolled.",
    birthDate: "22/03/2002",
    educationHistory: [
      {
        id: "0",
        degree: "MOCKED_DOMAIN",
        from: { day: 26, month: 9, year: 2022 },
        level: EducationLevel.COLLEGE,
        school: "MOCKED_COLLEGE",
        visibility: Permission.PUBLIC,
      },
      {
        id: "1",
        degree: "MOCKED_DOMAIN",
        from: { day: 24, month: 9, year: 2018 },
        graduated: true,
        level: EducationLevel.COLLEGE,
        school: "MOCKED_COLLEGE",
        to: { day: 21, month: 6, year: 2022 },
        visibility: Permission.FRIENDS,
      },
      {
        id: "2",
        from: { day: 15, month: 9, year: 2014 },
        graduated: true,
        level: EducationLevel.HIGH_SCHOOL,
        school: "MOCKED_HIGH_SCHOOL",
        to: { day: 31, month: 5, year: 2018 },
        visibility: Permission.ONLY_ME,
      },
    ],
    email: "olivia.constantin@mail.com",
    firstName: "Olivia",
    friends: [
      {
        id: "1",
        email: "darius.fieraru@mail.com",
        firstName: "Darius",
        lastName: "Fieraru",
        username: "darius.fieraru",
      },
      {
        id: "3",
        email: "gogu.filotti@mail.com",
        firstName: "Gogu",
        lastName: "Filotti",
        username: "gogu.filotti",
      },
    ],
    lastName: "Constantin",
    placesHistory: [
      {
        id: "0",
        city: "MOCKED_CITY",
        from: { day: 1, month: 8, year: 2022 },
        isCurrent: true,
        visibility: Permission.PUBLIC,
      },
    ],
    relationshipStatus: {
      status: RelationshipStatus.IT_IS_COMPLICATED,
      visibility: Permission.FRIENDS,
    },
    username: "olivia.constantin",
    workHistory: [
      {
        id: "0",
        company: "MOCKED_COMPANY",
        from: { day: 1, month: 8, year: 2022 },
        position: "MOCKED_POSITION_1",
        to: { day: 1, month: 2, year: 2023 },
        visibility: Permission.FRIENDS,
      },
      {
        id: "1",
        company: "MOCKED_COMPANY",
        from: { day: 2, month: 2, year: 2023 },
        isCurrent: true,
        position: "MOCKED_POSITION_2",
        visibility: Permission.ONLY_ME,
      },
    ],
  },
  {
    id: "1",
    birthDate: "13/05/2002",
    email: "darius.fieraru@mail.com",
    firstName: "Darius",
    friends: [
      {
        id: "0",
        email: "olivia.constantin@mail.com",
        firstName: "Olivia",
        lastName: "Constantin",
        username: "olivia.constantin",
      },
    ],
    lastName: "Fieraru",
    username: "darius.fieraru",
  },
  {
    id: "2",
    biography: "She was born in a loving family in an average port.",
    birthDate: "30/01/2005",
    email: "augustina.stanca@mail.com",
    firstName: "Augustina",
    lastName: "Stanca",
    username: "augustina.stanca",
  },
  {
    id: "3",
    biography:
      "He's pensive, clever and independent. This is to be expected from somebody with his terrible past.",
    birthDate: "01/01/2000",
    email: "gogu.filotti@mail.com",
    firstName: "Gogu",
    friends: [
      {
        id: "0",
        email: "olivia.constantin@mail.com",
        firstName: "Olivia",
        lastName: "Constantin",
        username: "olivia.constantin",
      },
      {
        id: "4",
        email: "jean.rosetti@mail.com",
        firstName: "Jean",
        lastName: "Rosetti",
        username: "jean.rosetti",
      },
    ],
    lastName: "Filotti",
    username: "gogu.filotti",
  },
  {
    id: "4",
    biography:
      "With the lessons of the past, he now works on travelling and surviving of nature.",
    birthDate: "14/02/1998",
    email: "jean.rosetti@mail.com",
    firstName: "Jean",
    friends: [
      {
        id: "3",
        email: "gogu.filotti@mail.com",
        firstName: "Gogu",
        lastName: "Filotti",
        username: "gogu.filotti",
      },
    ],
    lastName: "Rosetti",
    username: "jean.rosetti",
  },
  {
    id: "5",
    biography:
      "She lost her father in an act of terrorism and was shunned. With a childhood friend she had to survive in a wicked world.",
    birthDate: "28/09/1997",
    email: "tereza.teodorescu@mail.com",
    firstName: "Tereza",
    lastName: "Teodorescu",
    username: "tereza.teodorescu",
  },
];

module.exports = {
  AUTHENTICATED_USER_ID,
  COMMENTS_LIST,
  POST_PHOTOS_LIST,
  POSTS_LIST,
  USERS_LIST,
};
