export enum ConversationTheme {
  BLOOD = "BLOOD",
  CHINESE_YELLOW = "CHINESE_YELLOW",
  DEFAULT = "DEFAULT",
  INDIGO = "INDIGO",
  MAXIMUM_BLUE_PURPLE = "MAXIMUM_BLUE_PURPLE",
  OCEAN_BLUE = "OCEAN_BLUE",
  PURPLE_PIZZAZZ = "PURPLE_PIZZAZZ",
  RED = "RED",
  SUNSET_ORANGE = "SUNSET_ORANGE",
  SWEET_BROWN = "SWEET_BROWN",
  VERY_LIGH_BLUE = "VERY_LIGH_BLUE",
  VIVID_MALACHITE = "VIVID_MALACHITE",
}

export enum EducationLevel {
  COLLEGE = "COLLEGE",
  HIGH_SCHOOL = "HIGH_SCHOOL",
}

export enum Emoji {
  LIKE = "LIKE",
  LOVE = "LOVE",
}

export enum FriendshipStatus {
  FRIEND,
  FRIEND_REQUEST_RECEIVED,
  FRIEND_REQUEST_SENT,
  ME,
  NOT_FRIEND,
}

export enum MediaType {
  PHOTO = "PHOTO",
  VIDEO = "VIDEO",
}

export enum Month {
  JANUARY = "JANUARY",
  FEBRUARY = "FEBRUARY",
  MARCH = "MARCH",
  APRIL = "APRIL",
  MAY = "MAY",
  JUNE = "JUNE",
  JULY = "JULY",
  AUGUST = "AUGUST",
  SEPTEMBER = "SEPTEMBER",
  OCTOBER = "OCTOBER",
  NOVEMBER = "NOVEMBER",
  DECEMBER = "DECEMBER",
}

export enum Permission {
  FRIENDS = "FRIENDS",
  ONLY_ME = "ONLY_ME",
  PUBLIC = "PUBLIC",
}

export enum ReactionType {
  ANGRY = "ANGRY",
  CARE = "CARE",
  HAHA = "HAHA",
  LIKE = "LIKE",
  LOVE = "LOVE",
  SAD = "SAD",
  WOW = "WOW",
}

export enum RelationshipStatusType {
  SINGLE = "SINGLE",
  IN_A_RELATIONSHIP = "IN_A_RELATIONSHIP",
  ENGAGED = "ENGAGED",
  MARRIED = "MARRIED",
  IN_A_CIVIL_UNION = "IN_A_CIVIL_UNION",
  IN_A_DOMESTIC_PARTNERSHIP = "IN_A_DOMESTIC_PARTNERSHIP",
  IN_AN_OPEN_RELATIONSHIP = "IN_AN_OPEN_RELATIONSHIP",
  IT_IS_COMPLICATED = "IT_IS_COMPLICATED",
  SEPARATED = "SEPARATED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
}
